/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestordeconvivios;
import javax.swing.JOptionPane;

/**
 *
 * @author marcomiranda
 */
public class BarGuestList extends javax.swing.JFrame {
    
    GestorDeConvivios gdc;
    ListaLocais ll;

    /**
     * Creates new form BarGuestList
     */
    public BarGuestList(ListaLocais ll, GestorDeConvivios gdc) {
        
        this.ll = ll;
        this.gdc = gdc;
        
        initComponents();
        
        comboBoxBares.removeAllItems();
        
        for (Local l: gdc.getLocaisCoimbra()){
            if(l.getTipoLocal().equalsIgnoreCase("bar"))
                comboBoxBares.addItem(l.getNome());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuestListBarVoltar = new javax.swing.JButton();
        comboBoxBares = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaBarGuestList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuestListBarVoltar.setText("Voltar");
        btnGuestListBarVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuestListBarVoltarActionPerformed(evt);
            }
        });

        comboBoxBares.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxBares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxBaresActionPerformed(evt);
            }
        });

        txtAreaBarGuestList.setEditable(false);
        txtAreaBarGuestList.setColumns(20);
        txtAreaBarGuestList.setRows(5);
        jScrollPane1.setViewportView(txtAreaBarGuestList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnGuestListBarVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(comboBoxBares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBoxBares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnGuestListBarVoltar)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxBaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxBaresActionPerformed
        Local bar = gdc.getLocaisCoimbra().get(0);
        int lim, x;
        
        
        
        System.out.println(evt.getActionCommand());
        
        for (Local b: gdc.getLocaisCoimbra()) {
            if(b.getNome() == comboBoxBares.getSelectedItem()) {
                bar = b;
            }
        }
        
        x = 0;
        String text = "";
        
        txtAreaBarGuestList.setText(null);
        
        lim = bar.getGuestLimit();
  
        for (Inscricao i : gdc.getConvivios().get(0).getInscricoes()) {
                if (i.getLocal() == bar){
                    System.out.println(bar.getNome());
                    System.out.println(lim);
                    if(x == lim)
                        break;
                    x++;
                    text += i.getInscrito().getNome() + ", "
                        + i.getInscrito().getPerfil() + ", "
                        + i.getInscrito().getCurso() + "\n";
                
                txtAreaBarGuestList.setText(text);
                
                }
        }
    }//GEN-LAST:event_comboBoxBaresActionPerformed

    private void btnGuestListBarVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuestListBarVoltarActionPerformed
        
        this.setVisible(false);
        ll.setVisible(true);
        
    }//GEN-LAST:event_btnGuestListBarVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuestListBarVoltar;
    private javax.swing.JComboBox<String> comboBoxBares;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaBarGuestList;
    // End of variables declaration//GEN-END:variables
}
